# Generated by Django 2.2.1 on 2021-11-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default=None, max_length=255)),
                ('course', models.ManyToManyField(blank=True, default=None, to='web.Courses')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Department')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
