# Generated by Django 2.2.1 on 2021-11-03 18:48

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=50)),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chapter', models.IntegerField()),
                ('urls', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Courses')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(default=None, max_length=255)),
                ('mobile', models.CharField(default=None, max_length=100, null=True)),
                ('password', models.CharField(default=None, max_length=255)),
                ('intake', models.IntegerField()),
                ('section', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Department')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Smartbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chapter', models.IntegerField()),
                ('content', froala_editor.fields.FroalaField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Courses')),
            ],
            options={
                'db_table': 'smartbooks',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('mid-term', 'Mid-Term'), ('final', 'Final')], max_length=50)),
                ('question', models.CharField(max_length=255)),
                ('choice_1', models.CharField(max_length=255)),
                ('choice_2', models.CharField(max_length=255)),
                ('choice_3', models.CharField(max_length=255)),
                ('choice_4', models.CharField(max_length=255)),
                ('answer_no', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Courses')),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('enroll_type', models.CharField(default='Regular', max_length=100)),
                ('mid_term_marks', models.IntegerField(null=True)),
                ('final_marks', models.IntegerField(null=True)),
                ('total_marks', models.IntegerField(default=0)),
                ('created_at', models.DateField()),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Courses')),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Students')),
            ],
            options={
                'db_table': 'enroll',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Department'),
        ),
    ]
